# Generated by Django 3.2.8 on 2024-05-17 16:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Granja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('ubicacion', models.TextField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensores.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=200)),
                ('ubicacion', models.TextField(max_length=100)),
                ('granja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensores.granja')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('parametro', models.CharField(max_length=30)),
                ('maxValor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('minValor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ubicacion', models.TextField(max_length=100)),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensores.instalacion')),
            ],
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(default=datetime.datetime(2024, 5, 17, 11, 20, 3, 554278))),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensores.sensor')),
            ],
        ),
    ]
