# Generated by Django 3.2.8 on 2024-05-22 21:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='granja',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granjas', to='sensores.cliente'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='granja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalaciones', to='sensores.granja'),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2024, 5, 22, 16, 51, 53, 989939)),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='instalacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='sensores.instalacion'),
        ),
    ]
