# Generated by Django 5.0.6 on 2024-05-30 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0003_auto_20240522_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectura',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2024, 5, 30, 9, 30, 23, 868976)),
        ),
    ]
