# Generated by Django 5.0.6 on 2024-05-30 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0007_alter_lectura_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2024, 5, 30, 10, 5, 46, 624689)),
        ),
    ]
