# Generated by Django 5.0.6 on 2024-05-30 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0008_sensor_active_alter_lectura_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectura',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2024, 5, 30, 10, 14, 48, 346637)),
        ),
    ]
